name: sparkle_party
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <=3.3.1"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../_shared

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/buttons/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: fonts/TitilliumWeb-SemiBold.ttf
          weight: 600

