name: plant_forms
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  font_awesome_flutter: ^10.7.0
  provider:

  shared:
    path: ../_shared

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/
  fonts:
    - family: Barlow
      fonts:
        - asset: fonts/Barlow-Regular.otf
        - asset: fonts/Barlow-Medium.otf
          weight: 500
        - asset: fonts/Barlow-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/Barlow-SemiBold.otf
          weight: 600
        - asset: fonts/Barlow-Bold.otf
          weight: 700
        - asset: fonts/Barlow-ExtraBold.ttf
          weight: 800
    - family: Baloo
      fonts:
        - asset: fonts/Baloo-Regular.ttf